language: ruby
cache: bundler
sudo: false
install:
- bundle install
script:
- "./build-site.sh"
notifications:
  email:
    recipients:
    - holger@launchd.de
    on_success: change
    on_failure: always
env:
  global:
  - secure: swgMnwYX1wl8ure+Ozyt0Cf7b45ULN83ivY912fpnwkscM1WwKIoEu368CEe0smHcY6ORkB4LMzijEE5IHyG60x1fkMhphuQ/2lV8fzeRB2ABH0NtUUOFUmfJv2R1qyww5Nyu6Sn9VOzCa9sLYNWQOKwpkcOoGD/837d7ShA+zl3ypJ/IR89jgL+AEaOI+qTUtkSNC+bURZXlEfZvwUjZaX2yaTdYVTcYWiZeSh9cIJ73U/MANVlaufrCMbitQ1I7xzktzlqXVqh9wmTV7Xfjoz8/tVu2KNTLsuLSOGTx3IrO89Qr6U9zm4sQK6cR4E1ZdtIjsVfZ+QJkmnVz2Co5SuHzxieC0zXrXCO7uCID6JvkbG46+UNnJZLRXnVLUnuRVTWtU6lLgNUrbdbeug+vSKhGY3vHVYpoG0/lDvWreSPc6JhSCaRm3e6DxzYNIuq6zIwwSSLjergrva8mljud0LpQw7dVqiRKuAM5i35DNVneChkDF6ijQ0VpedixrDo5RwFDb6OxHUXLJhg7ic/eG4M8xZN9cSo8ZaHEeMhudjFsPAoxdXVRvG/P/WhbkhPJElbL2u54sWAKkLs59JyFoyO/AB61AgKPHYjJSQZM5PsSds2RsKpF1k9ECo6p3P6ZNv7kR2pQxkcqMuOSP3qu6V5NOAgieO2xGV7o84HqUc=
