# Site wide configuration

title: Holger Reinhardt
locale: en_US
description: I love building products.
logo: site-logo.png
search: true
comments: true
url: https://hlgr360.github.io/blog

# Jekyll configuration

permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

# Enter your Google Analytics web tracking code (e.g. UA-xxx) to activate tracking
google_analytics: UA-105145569-1

# Site owner
owner:
  name: Holger Reinhardt
  avatar: hlgr360.jpg
  email: holger@launchd.de
  disqus-shortname: hlgr360
  twitter: hlgr360
  facebook: #username
  github: hlgr360
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: hrreinhardt
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
